// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avxgduktxkorwfmccwbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2eGdkdWt0eGtvcndmbWNjd2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDYyNTYsImV4cCI6MjA1MDEyMjI1Nn0.1cxWtJ4-UOq2S2X0Nsw82EFTscaD3dgsysK7p4RwE54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);